### ISSUE TITLE
java.lang.NoSuchMethodError trying to run example

### ISSUE THREAD

**Issue by veenits** [sryza/spark-ts-examples#9]
Hi, 

I cloned the repository and did `mvn package`. I was able to build the jar but when I try to run the example from `jvm` folder by running `spark-submit --class com.cloudera.tsexamples.Stocks target/spark-ts-examples-0.0.1-SNAPSHOT-jar-with-dependencies.jar
`, I get the below exception - 

```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.SQLContext.createDataFrame(Lorg/apache/spark/rdd/RDD;Lorg/apache/spark/sql/types/StructType;)Lorg/apache/spark/sql/DataFrame;
	at com.cloudera.tsexamples.Stocks$.loadObservations(Stocks.scala:37)
	at com.cloudera.tsexamples.Stocks$.main(Stocks.scala:46)
	at com.cloudera.tsexamples.Stocks.main(Stocks.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by rajeshdoma** [comment]
r u able to resolve this?
